apiVersion: v1
kind: Service
metadata:
  name: wikimedia-mysql
  labels:
    app: wikimedia
spec:
  ports:
    - port: 3306
  selector:
    app: wikimedia
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: wikimedia
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: wikimedia-mysql
  labels:
    app: wikimedia
spec:
  selector:
    matchLabels:
      app: wikimedia
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wikimedia
        tier: mysql
    spec:
      containers:
      - image: mariadb:latest
        name: mysql
        lifecycle:
          postStart:
            exec:
              command: ["/bin/bash", "-c", "sleep 20 && mysql -u$MYSQL_USER -p$MYSQL_ROOT_PASSWORD < /scripts/create_user.sql > /dev/null 2>&1"]
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret-test
              key: password

        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret-test
              key: username

        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secret-test
              key: database
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        - name: app-db-script-vol
          mountPath: /scripts
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
      - name: app-db-script-vol
        configMap:
           name: appusers
           defaultMode: 0744
