---
- name: Deploy wikimedia
  include_tasks: deploy.yaml
  when: "'localhost' in inventory_hostname"

- name: minikube service url
  include_tasks: post-deploy.yaml
  hostvars[inventory_hostname].ec2_tag_type == "wikimedia-demo"
